  DROP TABLE IF EXISTS m04_saida_cnpj_metricas;
  CREATE TABLE m04_saida_cnpj_metricas (
    id serial4 NOT NULL,
    cnpj_completo text NULL,
    cnpj_prefixo text NULL,
    numero_participacoes_licitacoes bigint NULL,
    numero_participacoes_itens bigint NULL,
    numero_participacoes_orgaos bigint NULL,
    lista_orgaos_participacao text NULL,
    valor_total_lances float8 NULL,
    valor_minimo_lance float8 NULL,
    valor_maximo_lance float8 NULL,
    valor_medio_lance float8 NULL,
    numero_vitorias_licitacoes bigint NULL,
    numero_vitorias_itens bigint NULL,
    number_vitoria_orgaos bigint NULL,
    valor_total_vencido float8 NULL,
    valor_minimo_vencido float8 NULL,
    valor_maximo_vencido float8 NULL,
    valor_medio_vencido float8 NULL,
    taxa_de_retorno float8 NULL,
    numero_vinculos_societarios_outros_cnpjs bigint NULL,
    lista_cnpjs_vinculo_societario text NULL,
    numero_vinculos_societarios_licitacoes bigint NULL,
    lista_licitacoes_vinculo_societario text NULL,
    numero_vinculos_societarios_itens bigint NULL,
    lista_itens_vinculo_societario text NULL,
    numero_vinculos_societarios_cpf bigint NULL,
    lista_cpfs_vinculo_societario text NULL,
    numero_vinculos_endereco_outros_cnpjs bigint NULL,
    lista_cnpjs_vinculo_endereco text NULL,
    numero_vinculos_endereco_licitacoes bigint NULL,
    lista_licitacoes_vinculo_endereco text NULL,
    numero_vinculos_endereco_itens bigint NULL,
    lista_itens_vinculo_endereco text NULL,
    numero_vinculos_societarios bigint NULL,
    lista_vinculo_endereco text NULL,
    numero_vinculos_telefonicos_outros_cnpjs bigint NULL,
    lista_cnpjs_vinculo_telefonicos text NULL,
    numero_vinculos_telefonicos_licitacoes bigint NULL,
    lista_licitacoes_vinculo_telefonicos text NULL,
    numero_vinculos_telefonicos_itens bigint NULL,
    lista_itens_vinculo_telefonicos text NULL,
    numero_vinculos_telefonicos bigint NULL,
    lista_vinculo_telefonico text NULL,
    numero_filiais bigint NULL,
    numero_filiais_licitacoes bigint NULL,
    numero_filiais_itens bigint NULL,
    numero_minimo_competidores_licitacoes bigint NULL,
    numero_maximo_competidores_licitacoes bigint NULL,
    numero_medio_competidores_licitacoes float8 NULL,
    desvio_competidores_licitacoes float8 NULL,
    eh_competidor_frequente_licitacoes bool NULL,
    eh_competidor_frequente_itens bool NULL,
    indice_sucesso_licitacoes float8 NULL,
    indice_sucesso_itens float8 NULL,
    competiu_com_perdedor_frequente bool NULL,
    numero_perdedores_frequentes_que_competiu bigint NULL,
    lista_perdedores_frequentes_que_competiu text NULL,
    competiu_com_ganhador_frequente bool NULL,
    numero_ganhadores_frequentes_que_competiu bigint NULL,
    lista_ganhadores_frequentes_que_competiu text NULL,
    lista_de_concorrentes text NULL,
    eh_ganhador_frequente bool NULL,
    eh_perdedor_frequente bool NULL,
    nome_corporativo text NULL,
    nome_fantasia text NULL,
    data_inicial_atividade text NULL,
    codigo_fiscal_cnae text NULL,
    descricao_fiscal_cnae text NULL,
    descricao_endereco text NULL,
    tipo_endereco text NULL,
    numero_endereco text NULL,
    complemento_endereco text NULL,
    distrito_endereco text NULL,
    codigo_cep text NULL,
    estado_endereco text NULL,
    cidade_endereco text NULL,
    codigo_cidade_endereco text NULL,
    telefone_1 text NULL,
    telefone_2 text NULL,
    email text NULL,
    quantidade_parceiros text NULL,
    grau_conexao_corporativa bigint NULL,
    conexao_corporativa text NULL,
    grau_conexao_endereco bigint NULL,
    conexao_endereco text NULL,
    grau_conexao_telefonica bigint NULL,
    conexao_telefonica text NULL,
    criado_em timestamp NULL DEFAULT now()
  );
    
  DROP TABLE IF EXISTS m04_saida_dados_grupo;
  CREATE TABLE m04_saida_dados_grupo ( 
    id serial,
    chave text, 
    grupo bigint, 
    licitacao_id text, 
    item text,
    ano bigint, 
    mes bigint, 
    criado_em timestamp NULL DEFAULT now());

  DROP TABLE IF EXISTS m04_saida_rank_cnpjs_filiais;	
  CREATE TABLE m04_saida_rank_cnpjs_filiais(
    id serial,
    cnpj text, 
    participacoes text, 
    alarme float8, 
    criado_em timestamp NULL DEFAULT now());

  DROP TABLE IF EXISTS m04_saida_rank_cnpjs_matrizes;	  
  CREATE TABLE m04_saida_rank_cnpjs_matrizes(
    id serial,
    cnpj text, 
    participacoes text, 
    alarme float8, 
    criado_em timestamp NULL DEFAULT now());
    
  DROP TABLE IF EXISTS m04_saida_rank_cross_graph_quasi_cliques_filiais;	  
  CREATE TABLE m04_saida_rank_cross_graph_quasi_cliques_filiais(
      id serial,
      cnpjs text,
      grupos text,
      alarme float8,
      pesos_grupos text,
      criado_em timestamp NULL DEFAULT now()
  );

  DROP TABLE IF EXISTS m04_saida_rank_cross_graph_quasi_cliques_matrizes;	    
  CREATE TABLE m04_saida_rank_cross_graph_quasi_cliques_matrizes(
    id serial,
    cnpjs text, 
    grupos text, 
    alarme float8, 
    pesos_grupos text, 
    criado_em timestamp NULL DEFAULT now()
  );

  DROP TABLE IF EXISTS m04_itens_lote;	    
  CREATE TABLE m04_itens_lote(
    id_julgamento text, 
    id_licitacao text, 
    id_orgao text, 
    nome_orgao text, 
    nome_tipo_orgao text, 
    ano_exercicio text, 
    mes_licitacao text, 
    id_item_licitacao text, 
    nome_item text, 
    cod_item text, 
    num_item text, 
    num_lote bigint, 
    nome_lote text, 
    vlr_unitario float8, 
    num_quant_item float8, 
    vlr_perc_desconto float8, 
    vlr_perc_taxa_adm float8, 
    vlr_global float8, 
    num_cpf_cnpj_licitante text, 
    nome_licitante text, 
    cod_tipo_pessoa_licitante text, 
    cod_ibge_municipio text, 
    num_cpf_cnpj_municipio text, 
    nome_cidade text, 
    sigla_uf text, 
    class_item text, 
    id_licitacao_dataset text, 
    grupo bigint);

  DROP TABLE IF EXISTS m04_vencedores;	    
  CREATE TABLE m04_vencedores(
    id_licitacao text, 
    id_item_licitacao text, 
    id_orgao text, 
    ano_referencia bigint, 
    mes_exercicio bigint, 
    qtde_item_show float8, 
    vlr_unitario_show float8, 
    vlr_pct_desconto_show float8, 
    vlr_pct_tax_adm_show float8, 
    vlr_global_show float8, 
    num_cpf_cnpj_vencedor_show text, 
    cod_tipo_pessoa_vencedor text, 
    nome_vencedor_show text, 
    num_lote_show text, 
    dsc_lote_show text, 
    cod_item text, 
    num_item text, 
    dsc_item_show text, 
    dsc_unid_medida_show text, 
    id_licitacao_dataset text, 
    grupo bigint);
    
  DROP TABLE IF EXISTS m04_04_vinculo_sociedade_licitacoes;	      
  CREATE TABLE m04_04_vinculo_sociedade_licitacoes(
    num_cpf_cnpj1 text, 
    num_cpf_cnpj_matriz1 text, 
    num_cpf_cnpj2 text, 
    num_cpf_cnpj_matriz2 text, 
    id_licitacao text, 
    data_referencia text, 
    num_lote bigint, 
    id_item_licitacao text, 
    num_cpf_cnpj_socio text, 
    data_entrada_sociedade_cnpj1 text, 
    data_saida_sociedade_cnpj1 text, 
    data_entrada_sociedade_cnpj2 text, 
    data_saida_sociedade_cnpj2 text, 
    cnpj1_licitante boolean, 
    cnpj2_licitante boolean, 
    vinculo_direto boolean, 
    grupo bigint);

  DROP TABLE IF EXISTS m04_vinculo_endereco_licitacoes;	      
  CREATE TABLE m04_vinculo_endereco_licitacoes(
    id_licitacao text, 
    data_referencia text, 
    num_lote bigint, 
    id_item_licitacao text, 
    num_cpf_cnpj1 text, 
    num_cpf_cnpj_matriz1 text, 
    nome_matriz1 text, 
    num_cpf_cnpj2 text, 
    num_cpf_cnpj_matriz2 text, 
    nome_matriz2 text, 
    descricao_tipo_logradouro text, 
    logradouro text, 
    numero bigint, 
    complemento1 text, 
    complemento2 text, 
    flag_complemento_igual boolean, 
    bairro text, 
    cep text, 
    uf text, 
    cod_municipio_siafi text, 
    cod_municipio_ibge text, 
    nome_municipio text, 
    data_inicio1 text, 
    data_fim1 text, 
    data_inicio2 text, 
    data_fim2 text, 
    grupo bigint);
    
    DROP TABLE IF EXISTS m04_vinculo_telefone_licitacoes;	      
    CREATE TABLE m04_vinculo_telefone_licitacoes(
    id_licitacao text, 
    data_referencia text, 
    num_lote text, 
    id_item_licitacao text, 
    num_cpf_cnpj1 text, 
    num_cpf_cnpj_matriz1 text, 
    nome_matriz1 text, 
    num_cpf_cnpj2 text, 
    num_cpf_cnpj_matriz2 text, 
    nome_matriz2 text, 
    ddd_telefone text, 
    data_inicio1 text, 
    data_fim1 text, 
    data_inicio2 text, 
    data_fim2 text, 
    grupo bigint);
    
    DROP TABLE IF EXISTS m04_vinculo_matriz_filial;	      
    CREATE TABLE m04_vinculo_matriz_filial(
    id_licitacao text, 
    id_item_licitacao text, 
    prefixo_cnpj text, 
    num_filiais bigint, 
    grupo bigint)